name: Bug Report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug clearly
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click...
        3. See error
    validations:
      required: true

  - type: input
    attributes:
      label: Environment
      placeholder: "OS, browser, app version"
