name: Bug Report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug","Fixed","Need to Discuss","Hold","To Be Tested","High Priority", "Work In Progress"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug clearly
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click...
        3. See error
    validations:
      required: true

  - type: input
    attributes:
      label: Environment
      placeholder: "OS, browser, app version"

  - type: input
    attributes:
      label: Version
      description: Version number where the bug occurred
      placeholder: "e.g., v1.0.0"
    validations:
      required: true
